name: API push build
on:
  push:
    branches:
      - main
jobs:
  api-journeys:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@main
    with:
      name: api-journeys
      repository: jfp-api-journeys-prod
      seed_repository: jfp-api-journeys-seed-prod
      branch: ${{ github.ref_name }}
      ecs_cluster: jfp-ecs-cluster-prod
      ecs_service: api-journeys-prod-service
      seed_task_name: api-journeys-seed-prod
      endpoint_url: http://api-journeys.service.internal:4001/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARCLIGHT_API_KEY: ${{ secrets.ARCLIGHT_API_KEY }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
      AWS_NETWORK_CONFIG: ${{ secrets.AWS_NETWORK_CONFIG }}
  api-users:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@main
    with:
      name: api-users
      repository: jfp-api-users-prod
      seed_repository: jfp-api-users-seed-prod
      branch: ${{ github.ref_name }}
      ecs_cluster: jfp-ecs-cluster-prod
      ecs_service: api-users-prod-service
      seed_task_name: api-users-seed-prod
      endpoint_url: http://api-users.service.internal:4002/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARCLIGHT_API_KEY: ${{ secrets.ARCLIGHT_API_KEY }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
      AWS_NETWORK_CONFIG: ${{ secrets.AWS_NETWORK_CONFIG }}
  api-languages:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@main
    with:
      name: api-languages
      repository: jfp-api-languages-prod
      seed_repository: jfp-api-languages-seed-prod
      branch: ${{ github.ref_name }}
      ecs_cluster: jfp-ecs-cluster-prod
      ecs_service: api-languages-prod-service
      seed_task_name: api-languages-seed-prod
      endpoint_url: http://api-languages.service.internal:4003/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARCLIGHT_API_KEY: ${{ secrets.ARCLIGHT_API_KEY }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
      AWS_NETWORK_CONFIG: ${{ secrets.AWS_NETWORK_CONFIG }}
  api-videos:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@main
    with:
      name: api-videos
      repository: jfp-api-videos-prod
      seed_repository: jfp-api-videos-seed-prod
      branch: ${{ github.ref_name }}
      ecs_cluster: jfp-ecs-cluster-prod
      ecs_service: api-videos-prod-service
      seed_task_name: api-videos-seed-prod
      endpoint_url: http://api-videos.service.internal:4004/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARCLIGHT_API_KEY: ${{ secrets.ARCLIGHT_API_KEY }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
      AWS_NETWORK_CONFIG: ${{ secrets.AWS_NETWORK_CONFIG }}
  api-media:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@main
    with:
      name: api-media
      repository: jfp-api-media-prod
      branch: ${{ github.ref_name }}
      ecs_cluster: jfp-ecs-cluster-prod
      ecs_service: api-media-prod-service
      endpoint_url: http://api-media.service.internal:4005/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARCLIGHT_API_KEY: ${{ secrets.ARCLIGHT_API_KEY }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
      AWS_NETWORK_CONFIG: ${{ secrets.AWS_NETWORK_CONFIG }}
  api-gateway:
    uses: JesusFilm/core/.github/workflows/api-gateway-prod-worker.yml@main
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      JFP_AWS_ACCESS_KEY_ID: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
      JFP_AWS_SECRET_ACCESS_KEY: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
